[package]
name = "_15_1_criterion_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.0"  # For random number generation in benchmarks

[dev-dependencies]
criterion = { version = "0.5.1" }  # Add Criterion as a development dependency

[[bench]]
name = "my_benchmark"
harness = false
